---
title: "01_load.qmd"
format: html
editor: visual
---

## Load packages

```{r}
#| output: false
#| warning: false
library(tidyverse)
library(httr)
```

## Creating data folder if not already exists

If the data folder and subfolder \_raw does not already exist, this code will create it.

```{r}
#| output: false
#| warning: false
# setting up main directory 
main_dir <- ".." 

# setting up the data directory
data_dir <- "data"
raw_dir <- "data/_raw"

if (file.exists("data")) { 
  
    # specifying the working directory 
    setwd(file.path(main_dir)) 
  
} else { 
    
    # create data directory inside main path 
    dir.create(file.path(main_dir, data_dir))
  
    # create _raw directory inside data
    dir.create(file.path(main_dir, raw_dir))
  }
```

## Download meta data

```{r}
#| warning: false
meta_url <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE31nnn/GSE31684/suppl/GSE31684%5Ftable%5Fof%5Fclinical%5Fdetails.txt.gz"

# setting working directory
setwd(file.path(".."))


if (file.exists("data/_raw/GSE31684_meta_data.tsv")){
  
  # Unzip and read the contents using tidyverse functions
  meta_data <- read_tsv("data/_raw/GSE31684_meta_data.tsv",
                        show_col_types = FALSE)
  
} else {
  # Download the gzipped file
  GET(meta_url, write_disk("data/_raw/GSE31684_meta_data.tsv"
                           ))
  
  # Unzip and read the contents using tidyverse functions
  meta_data <- read_tsv(gzfile("data/_raw/GSE31684_meta_data.tsv"),  show_col_types = FALSE)
}
                          
# View the first few rows of the data
meta_data
```

## Download gene expression data

```{r}
# creating url
gene_url <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE31nnn/GSE31684/matrix/GSE31684_series_matrix.txt.gz"

# this is necessary to not get error message about connection buffer
Sys.setenv(VROOM_CONNECTION_SIZE=500000)

# Retrieve the data directly
# skippin first 82 lines because it is just info
gene_exp_file <- read_tsv(file = gene_url,
                          skip = 82)

# Write the data to disk
write_tsv(x = gene_exp_file,
          file = "../data/_raw/gene_exp.tsv")

gene_exp_data <- read_tsv("../data/_raw/gene_exp.tsv")

gene_exp_data
```

```{r}
# Removed last line:
gene_exp_data <- gene_exp_data |> 
  filter(!str_detect(ID_REF, "^!"))

# Create data subset:
gene_exp_subset <- gene_exp_data |> 
  slice_sample(n=5000)
```

```{r}
# Transpose the data table:
df_long <- gene_exp_subset %>%
  pivot_longer(cols = -ID_REF, names_to = "GEO", values_to = "Value")

# Transpose the dataframe from long to wide format
df_wide <- df_long %>%
  pivot_wider(names_from = ID_REF, values_from = Value)
```

```{r}
# Join metadata and gene expresison data based on patient ID:
data_joined = full_join(meta_data, df_wide, by = join_by(GEO))
```

```{r}
write_tsv(data_joined, "../data/data_joined.tsv")
```
