---
title: "02_clean.qmd"
format:
  html:
    embed-resources: true
author: "Sarah Rosenberg Asmussen (s194689),	Mette Bøge Pedersen (s194679),	Caroline Amalie Bastholm Jensen (s213427), Jaime Noguera Piera (s233773), Yassine Turki (s231735)"
editor: visual
---

## Loading Packages:

```{r}
library(tidyverse) 
library(httr) 
library(readr)
```

## Load Data:

```{r}
data <- read_tsv("../data/01_dat_load.tsv")  
head(data)
```

## Clean Data:

We select two attributes relevant to our analysis: Metastasis and Smoking, as well as gene expressions

```{r}
# Cleaning the data: 
data_clean <- data |> 
  relocate(Metastasis, Smoking) |>   
  select(!GEO:Cluster)


# Making the dataset long:
data_clean_long <- data_clean |>    
  pivot_longer(cols=-c(Metastasis, Smoking),
               names_to = "gene",
               values_to = "gene_expression")   

data_clean_long
```

We would like to drop the genes with no variability, as they will not provide useful information to our analysis.

```{r}

# Selecting genes with different average gene expression based on the metastatic and non-metastatic cases:
data_clean_long <- data_clean_long |>
  group_by(gene) |>
  filter(sd(gene_expression)!=0)

  
data_clean_long
```

## Writing the data

```{r}
write_tsv(data_clean_long, "../data/02_dat_clean.tsv")
```
