```{r}

#| output: false
#| warning: false
library(tidyverse)
library(httr)
library(readr)

```

```{r}
#| output: false
#| warning: false
data <- read_tsv("../data/data_joined.tsv")
```

```{r}
data
```

```{r}
data |>
    summarise_all(class) |>
    gather(variable, class) |>
    filter(class == "character") |>
    mutate(unique_values = sapply(data[, variable], function(x) length(unique(x))))
```

We count how many NA's we have:

```{r}
data |>
  map(is.na)|>
  map(sum) |>
  keep(~ . != 0)
```

We transform the NA's into 0:

```{r}

data_na_dropped <- data |>
mutate(across(everything(), ~ifelse(is.na(.), 0, .)))
```

We encode binary data to have it as numeric

```{r}
data_geneexp <- data |>
   mutate(across(everything(), ~ ifelse(. %in% c("No", "male", "Low"), 0, .))) |>
   mutate(across(everything(), ~ ifelse(. %in% c("Yes", "female", "High"), 1, .)))


```

We drop the ID column, not useful to our analysis

```{r}
data_geneexp <- data_geneexp |>
  select(-"ID")
```

```{r}
tail(data_geneexp)
```

```{r}
unique_values <- unique(data_geneexp$"PostChemo type")
print(unique_values)
```
