## Volcane plot

### Loading libraires
```{r}
library(tidyverse)
library(ggrepel)
```

### Generating estimates variable

```{r}
data_estimate <- data_aug_log |>
  mutate(estimate = mean(log2_fold_change)) |>
  distinct(gene, .keep_all = TRUE) |>
  mutate(log_10_p = -log10(p_value))
```

```{r}
set.seed(62)

data_estimate |>
  filter(!is.na(estimate), !is.na(log_10_p)) |>
  sample_n(5) |> # I randomly limit the number of data points to be plotted
  
  ggplot(mapping = aes(x = estimate, 
                     y = log_10_p,
                     label = significant_gene,
                     color = is_significant)) +
  
  geom_point(size = 1, alpha = 0.5) +
    xlim(-0.1,0.1) +
  
  ylim(0,4) +
  
  geom_text_repel(size = 2, max.overlaps = 50) +
  
  theme_minimal() +
  
  labs(title="Metastasis",
     x = "Estimates", 
     y = "-log10(p)") +
  
  theme(legend.position = "none", 
        plot.title = element_text(size = 13,
                                  hjust = 0.5),
        plot.subtitle = element_text(size = 11,
                                     hjust = 1),
        axis.line.x.bottom = element_line(color="black"))

dswdw
```